### ISSUE TITLE
Add sector-spanning IT interconnectivity between Liberale Gamer Gameserver and Mitgliedersystem

### ISSUE THREAD

**Issue by FranziskaSeitz** [Liberale-Gamer/liga_mitglieder#69]

**Comment by marvinruder** [comment]
@Sentexi Can you provide a list of all relevant services and their ID when accessing them using `systemctl`?

**Comment by Sentexi** [comment]
ts3.service - Teamspeak
mc_server.service -Minecraft
sharelatex.service - Overleaf 
ttt.service - Gmod Server (currently running TTT)
rocketchat.service - Rocketchat (does anybody still use this..?)
jicofo.service , jitsi-videobridge2.service, prosody.service - Jitsi Infrastructure
mongod.service - MongoDB Server (mostly used for rocketchat atm)
mysql.service - MySQL Server
openslides.service - Openslides Server

**Comment by FranziskaSeitz** [comment]
Add respective server adresses eg. teamspeak.

**Comment by Sentexi** [comment]
ts3.service - Teamspeak - liberale-gamer.gg
mc_server.service -Minecraft - liberale-gamer.gg
sharelatex.service - Overleaf - overleaf.liberale-gamer.gg
ttt.service - Gmod Server (currently running TTT) liberale-gamer.gg
rocketchat.service - Rocketchat (does anybody still use this..?) chat.liberale-gamer.gg
jicofo.service , jitsi-videobridge2.service, prosody.service - Jitsi Infrastructure event.liberale-gamer.gg
mongod.service - MongoDB Server (mostly used for rocketchat atm) liberale-gamer.gg
mysql.service - MySQL Server liberale-gamer.gg
openslides.service - Openslides Server openslides.liberale-gamer.gg
